//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MES_Web_Services.N2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="erp_servicesSoap11Binding", Namespace="http://erpwss.webservices.services.aisino.morelean.com")]
    public partial class erp_services : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback syncPurchaseOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncWarehouseInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncAccountAliasInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncTestInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncCheckFinishAllStationOperationCompleted;
        
        private System.Threading.SendOrPostCallback beTrueOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncInStockDocInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncIMEIInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncSaveMidInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncSupplierInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncProductOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncOutStockDocInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncCheckStationOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncAllotDocInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncSalesOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncMaterialInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback replaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncBomInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncSetStationOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncUploadParametersOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncProductMaterialInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public erp_services() {
            this.Url = global::MES_Web_Services.Properties.Settings.Default.MES_Web_Services_N2_erp_services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event syncPurchaseOrderInfoCompletedEventHandler syncPurchaseOrderInfoCompleted;
        
        /// <remarks/>
        public event syncWarehouseInfoCompletedEventHandler syncWarehouseInfoCompleted;
        
        /// <remarks/>
        public event syncAccountAliasInfoCompletedEventHandler syncAccountAliasInfoCompleted;
        
        /// <remarks/>
        public event syncTestInfoCompletedEventHandler syncTestInfoCompleted;
        
        /// <remarks/>
        public event syncCheckFinishAllStationCompletedEventHandler syncCheckFinishAllStationCompleted;
        
        /// <remarks/>
        public event beTrueCompletedEventHandler beTrueCompleted;
        
        /// <remarks/>
        public event syncOrderInfoCompletedEventHandler syncOrderInfoCompleted;
        
        /// <remarks/>
        public event syncInStockDocInfoCompletedEventHandler syncInStockDocInfoCompleted;
        
        /// <remarks/>
        public event syncIMEIInfoCompletedEventHandler syncIMEIInfoCompleted;
        
        /// <remarks/>
        public event syncSaveMidInfoCompletedEventHandler syncSaveMidInfoCompleted;
        
        /// <remarks/>
        public event syncSupplierInfoCompletedEventHandler syncSupplierInfoCompleted;
        
        /// <remarks/>
        public event syncProductOrderInfoCompletedEventHandler syncProductOrderInfoCompleted;
        
        /// <remarks/>
        public event syncOutStockDocInfoCompletedEventHandler syncOutStockDocInfoCompleted;
        
        /// <remarks/>
        public event syncCheckStationCompletedEventHandler syncCheckStationCompleted;
        
        /// <remarks/>
        public event syncAllotDocInfoCompletedEventHandler syncAllotDocInfoCompleted;
        
        /// <remarks/>
        public event syncSalesOrderInfoCompletedEventHandler syncSalesOrderInfoCompleted;
        
        /// <remarks/>
        public event syncCustomerInfoCompletedEventHandler syncCustomerInfoCompleted;
        
        /// <remarks/>
        public event syncMaterialInfoCompletedEventHandler syncMaterialInfoCompleted;
        
        /// <remarks/>
        public event replaceCompletedEventHandler replaceCompleted;
        
        /// <remarks/>
        public event syncBomInfoCompletedEventHandler syncBomInfoCompleted;
        
        /// <remarks/>
        public event syncSetStationCompletedEventHandler syncSetStationCompleted;
        
        /// <remarks/>
        public event syncUploadParametersCompletedEventHandler syncUploadParametersCompleted;
        
        /// <remarks/>
        public event syncProductMaterialInfoCompletedEventHandler syncProductMaterialInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncPurchaseOrderInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncPurchaseOrderInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncPurchaseOrderInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncPurchaseOrderInfoAsync(string args0) {
            this.syncPurchaseOrderInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncPurchaseOrderInfoAsync(string args0, object userState) {
            if ((this.syncPurchaseOrderInfoOperationCompleted == null)) {
                this.syncPurchaseOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncPurchaseOrderInfoOperationCompleted);
            }
            this.InvokeAsync("syncPurchaseOrderInfo", new object[] {
                        args0}, this.syncPurchaseOrderInfoOperationCompleted, userState);
        }
        
        private void OnsyncPurchaseOrderInfoOperationCompleted(object arg) {
            if ((this.syncPurchaseOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncPurchaseOrderInfoCompleted(this, new syncPurchaseOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncWarehouseInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncWarehouseInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncWarehouseInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncWarehouseInfoAsync(string args0) {
            this.syncWarehouseInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncWarehouseInfoAsync(string args0, object userState) {
            if ((this.syncWarehouseInfoOperationCompleted == null)) {
                this.syncWarehouseInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncWarehouseInfoOperationCompleted);
            }
            this.InvokeAsync("syncWarehouseInfo", new object[] {
                        args0}, this.syncWarehouseInfoOperationCompleted, userState);
        }
        
        private void OnsyncWarehouseInfoOperationCompleted(object arg) {
            if ((this.syncWarehouseInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncWarehouseInfoCompleted(this, new syncWarehouseInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncAccountAliasInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncAccountAliasInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncAccountAliasInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncAccountAliasInfoAsync(string args0) {
            this.syncAccountAliasInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncAccountAliasInfoAsync(string args0, object userState) {
            if ((this.syncAccountAliasInfoOperationCompleted == null)) {
                this.syncAccountAliasInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncAccountAliasInfoOperationCompleted);
            }
            this.InvokeAsync("syncAccountAliasInfo", new object[] {
                        args0}, this.syncAccountAliasInfoOperationCompleted, userState);
        }
        
        private void OnsyncAccountAliasInfoOperationCompleted(object arg) {
            if ((this.syncAccountAliasInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncAccountAliasInfoCompleted(this, new syncAccountAliasInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncTestInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncTestInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncTestInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncTestInfoAsync(string args0) {
            this.syncTestInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncTestInfoAsync(string args0, object userState) {
            if ((this.syncTestInfoOperationCompleted == null)) {
                this.syncTestInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncTestInfoOperationCompleted);
            }
            this.InvokeAsync("syncTestInfo", new object[] {
                        args0}, this.syncTestInfoOperationCompleted, userState);
        }
        
        private void OnsyncTestInfoOperationCompleted(object arg) {
            if ((this.syncTestInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncTestInfoCompleted(this, new syncTestInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncCheckFinishAllStation", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncCheckFinishAllStation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncCheckFinishAllStation", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncCheckFinishAllStationAsync(string args0) {
            this.syncCheckFinishAllStationAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncCheckFinishAllStationAsync(string args0, object userState) {
            if ((this.syncCheckFinishAllStationOperationCompleted == null)) {
                this.syncCheckFinishAllStationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncCheckFinishAllStationOperationCompleted);
            }
            this.InvokeAsync("syncCheckFinishAllStation", new object[] {
                        args0}, this.syncCheckFinishAllStationOperationCompleted, userState);
        }
        
        private void OnsyncCheckFinishAllStationOperationCompleted(object arg) {
            if ((this.syncCheckFinishAllStationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncCheckFinishAllStationCompleted(this, new syncCheckFinishAllStationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:beTrue", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string beTrue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("beTrue", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void beTrueAsync(string args0) {
            this.beTrueAsync(args0, null);
        }
        
        /// <remarks/>
        public void beTrueAsync(string args0, object userState) {
            if ((this.beTrueOperationCompleted == null)) {
                this.beTrueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbeTrueOperationCompleted);
            }
            this.InvokeAsync("beTrue", new object[] {
                        args0}, this.beTrueOperationCompleted, userState);
        }
        
        private void OnbeTrueOperationCompleted(object arg) {
            if ((this.beTrueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.beTrueCompleted(this, new beTrueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncOrderInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncOrderInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncOrderInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncOrderInfoAsync(string args0) {
            this.syncOrderInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncOrderInfoAsync(string args0, object userState) {
            if ((this.syncOrderInfoOperationCompleted == null)) {
                this.syncOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncOrderInfoOperationCompleted);
            }
            this.InvokeAsync("syncOrderInfo", new object[] {
                        args0}, this.syncOrderInfoOperationCompleted, userState);
        }
        
        private void OnsyncOrderInfoOperationCompleted(object arg) {
            if ((this.syncOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncOrderInfoCompleted(this, new syncOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncInStockDocInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncInStockDocInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncInStockDocInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncInStockDocInfoAsync(string args0) {
            this.syncInStockDocInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncInStockDocInfoAsync(string args0, object userState) {
            if ((this.syncInStockDocInfoOperationCompleted == null)) {
                this.syncInStockDocInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncInStockDocInfoOperationCompleted);
            }
            this.InvokeAsync("syncInStockDocInfo", new object[] {
                        args0}, this.syncInStockDocInfoOperationCompleted, userState);
        }
        
        private void OnsyncInStockDocInfoOperationCompleted(object arg) {
            if ((this.syncInStockDocInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncInStockDocInfoCompleted(this, new syncInStockDocInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncIMEIInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncIMEIInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncIMEIInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncIMEIInfoAsync(string args0) {
            this.syncIMEIInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncIMEIInfoAsync(string args0, object userState) {
            if ((this.syncIMEIInfoOperationCompleted == null)) {
                this.syncIMEIInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncIMEIInfoOperationCompleted);
            }
            this.InvokeAsync("syncIMEIInfo", new object[] {
                        args0}, this.syncIMEIInfoOperationCompleted, userState);
        }
        
        private void OnsyncIMEIInfoOperationCompleted(object arg) {
            if ((this.syncIMEIInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncIMEIInfoCompleted(this, new syncIMEIInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncSaveMidInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncSaveMidInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncSaveMidInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncSaveMidInfoAsync(string args0) {
            this.syncSaveMidInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncSaveMidInfoAsync(string args0, object userState) {
            if ((this.syncSaveMidInfoOperationCompleted == null)) {
                this.syncSaveMidInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncSaveMidInfoOperationCompleted);
            }
            this.InvokeAsync("syncSaveMidInfo", new object[] {
                        args0}, this.syncSaveMidInfoOperationCompleted, userState);
        }
        
        private void OnsyncSaveMidInfoOperationCompleted(object arg) {
            if ((this.syncSaveMidInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncSaveMidInfoCompleted(this, new syncSaveMidInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncSupplierInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncSupplierInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncSupplierInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncSupplierInfoAsync(string args0) {
            this.syncSupplierInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncSupplierInfoAsync(string args0, object userState) {
            if ((this.syncSupplierInfoOperationCompleted == null)) {
                this.syncSupplierInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncSupplierInfoOperationCompleted);
            }
            this.InvokeAsync("syncSupplierInfo", new object[] {
                        args0}, this.syncSupplierInfoOperationCompleted, userState);
        }
        
        private void OnsyncSupplierInfoOperationCompleted(object arg) {
            if ((this.syncSupplierInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncSupplierInfoCompleted(this, new syncSupplierInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncProductOrderInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncProductOrderInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncProductOrderInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncProductOrderInfoAsync(string args0) {
            this.syncProductOrderInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncProductOrderInfoAsync(string args0, object userState) {
            if ((this.syncProductOrderInfoOperationCompleted == null)) {
                this.syncProductOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncProductOrderInfoOperationCompleted);
            }
            this.InvokeAsync("syncProductOrderInfo", new object[] {
                        args0}, this.syncProductOrderInfoOperationCompleted, userState);
        }
        
        private void OnsyncProductOrderInfoOperationCompleted(object arg) {
            if ((this.syncProductOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncProductOrderInfoCompleted(this, new syncProductOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncOutStockDocInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncOutStockDocInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncOutStockDocInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncOutStockDocInfoAsync(string args0) {
            this.syncOutStockDocInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncOutStockDocInfoAsync(string args0, object userState) {
            if ((this.syncOutStockDocInfoOperationCompleted == null)) {
                this.syncOutStockDocInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncOutStockDocInfoOperationCompleted);
            }
            this.InvokeAsync("syncOutStockDocInfo", new object[] {
                        args0}, this.syncOutStockDocInfoOperationCompleted, userState);
        }
        
        private void OnsyncOutStockDocInfoOperationCompleted(object arg) {
            if ((this.syncOutStockDocInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncOutStockDocInfoCompleted(this, new syncOutStockDocInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncCheckStation", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncCheckStation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncCheckStation", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncCheckStationAsync(string args0) {
            this.syncCheckStationAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncCheckStationAsync(string args0, object userState) {
            if ((this.syncCheckStationOperationCompleted == null)) {
                this.syncCheckStationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncCheckStationOperationCompleted);
            }
            this.InvokeAsync("syncCheckStation", new object[] {
                        args0}, this.syncCheckStationOperationCompleted, userState);
        }
        
        private void OnsyncCheckStationOperationCompleted(object arg) {
            if ((this.syncCheckStationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncCheckStationCompleted(this, new syncCheckStationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncAllotDocInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncAllotDocInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncAllotDocInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncAllotDocInfoAsync(string args0) {
            this.syncAllotDocInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncAllotDocInfoAsync(string args0, object userState) {
            if ((this.syncAllotDocInfoOperationCompleted == null)) {
                this.syncAllotDocInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncAllotDocInfoOperationCompleted);
            }
            this.InvokeAsync("syncAllotDocInfo", new object[] {
                        args0}, this.syncAllotDocInfoOperationCompleted, userState);
        }
        
        private void OnsyncAllotDocInfoOperationCompleted(object arg) {
            if ((this.syncAllotDocInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncAllotDocInfoCompleted(this, new syncAllotDocInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncSalesOrderInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncSalesOrderInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncSalesOrderInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncSalesOrderInfoAsync(string args0) {
            this.syncSalesOrderInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncSalesOrderInfoAsync(string args0, object userState) {
            if ((this.syncSalesOrderInfoOperationCompleted == null)) {
                this.syncSalesOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncSalesOrderInfoOperationCompleted);
            }
            this.InvokeAsync("syncSalesOrderInfo", new object[] {
                        args0}, this.syncSalesOrderInfoOperationCompleted, userState);
        }
        
        private void OnsyncSalesOrderInfoOperationCompleted(object arg) {
            if ((this.syncSalesOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncSalesOrderInfoCompleted(this, new syncSalesOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncCustomerInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncCustomerInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncCustomerInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncCustomerInfoAsync(string args0) {
            this.syncCustomerInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncCustomerInfoAsync(string args0, object userState) {
            if ((this.syncCustomerInfoOperationCompleted == null)) {
                this.syncCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("syncCustomerInfo", new object[] {
                        args0}, this.syncCustomerInfoOperationCompleted, userState);
        }
        
        private void OnsyncCustomerInfoOperationCompleted(object arg) {
            if ((this.syncCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncCustomerInfoCompleted(this, new syncCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncMaterialInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncMaterialInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncMaterialInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncMaterialInfoAsync(string args0) {
            this.syncMaterialInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncMaterialInfoAsync(string args0, object userState) {
            if ((this.syncMaterialInfoOperationCompleted == null)) {
                this.syncMaterialInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncMaterialInfoOperationCompleted);
            }
            this.InvokeAsync("syncMaterialInfo", new object[] {
                        args0}, this.syncMaterialInfoOperationCompleted, userState);
        }
        
        private void OnsyncMaterialInfoOperationCompleted(object arg) {
            if ((this.syncMaterialInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncMaterialInfoCompleted(this, new syncMaterialInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:replace", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string replace([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("replace", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void replaceAsync(string args0) {
            this.replaceAsync(args0, null);
        }
        
        /// <remarks/>
        public void replaceAsync(string args0, object userState) {
            if ((this.replaceOperationCompleted == null)) {
                this.replaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreplaceOperationCompleted);
            }
            this.InvokeAsync("replace", new object[] {
                        args0}, this.replaceOperationCompleted, userState);
        }
        
        private void OnreplaceOperationCompleted(object arg) {
            if ((this.replaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.replaceCompleted(this, new replaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncBomInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncBomInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncBomInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncBomInfoAsync(string args0) {
            this.syncBomInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncBomInfoAsync(string args0, object userState) {
            if ((this.syncBomInfoOperationCompleted == null)) {
                this.syncBomInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncBomInfoOperationCompleted);
            }
            this.InvokeAsync("syncBomInfo", new object[] {
                        args0}, this.syncBomInfoOperationCompleted, userState);
        }
        
        private void OnsyncBomInfoOperationCompleted(object arg) {
            if ((this.syncBomInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncBomInfoCompleted(this, new syncBomInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncSetStation", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncSetStation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncSetStation", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncSetStationAsync(string args0) {
            this.syncSetStationAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncSetStationAsync(string args0, object userState) {
            if ((this.syncSetStationOperationCompleted == null)) {
                this.syncSetStationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncSetStationOperationCompleted);
            }
            this.InvokeAsync("syncSetStation", new object[] {
                        args0}, this.syncSetStationOperationCompleted, userState);
        }
        
        private void OnsyncSetStationOperationCompleted(object arg) {
            if ((this.syncSetStationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncSetStationCompleted(this, new syncSetStationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncUploadParameters", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncUploadParameters([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncUploadParameters", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncUploadParametersAsync(string args0) {
            this.syncUploadParametersAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncUploadParametersAsync(string args0, object userState) {
            if ((this.syncUploadParametersOperationCompleted == null)) {
                this.syncUploadParametersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncUploadParametersOperationCompleted);
            }
            this.InvokeAsync("syncUploadParameters", new object[] {
                        args0}, this.syncUploadParametersOperationCompleted, userState);
        }
        
        private void OnsyncUploadParametersOperationCompleted(object arg) {
            if ((this.syncUploadParametersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncUploadParametersCompleted(this, new syncUploadParametersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncProductMaterialInfo", RequestNamespace="http://erpwss.webservices.services.aisino.morelean.com", ResponseNamespace="http://erpwss.webservices.services.aisino.morelean.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncProductMaterialInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0) {
            object[] results = this.Invoke("syncProductMaterialInfo", new object[] {
                        args0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncProductMaterialInfoAsync(string args0) {
            this.syncProductMaterialInfoAsync(args0, null);
        }
        
        /// <remarks/>
        public void syncProductMaterialInfoAsync(string args0, object userState) {
            if ((this.syncProductMaterialInfoOperationCompleted == null)) {
                this.syncProductMaterialInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncProductMaterialInfoOperationCompleted);
            }
            this.InvokeAsync("syncProductMaterialInfo", new object[] {
                        args0}, this.syncProductMaterialInfoOperationCompleted, userState);
        }
        
        private void OnsyncProductMaterialInfoOperationCompleted(object arg) {
            if ((this.syncProductMaterialInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncProductMaterialInfoCompleted(this, new syncProductMaterialInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncPurchaseOrderInfoCompletedEventHandler(object sender, syncPurchaseOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncPurchaseOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncPurchaseOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncWarehouseInfoCompletedEventHandler(object sender, syncWarehouseInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncWarehouseInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncWarehouseInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncAccountAliasInfoCompletedEventHandler(object sender, syncAccountAliasInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncAccountAliasInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncAccountAliasInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncTestInfoCompletedEventHandler(object sender, syncTestInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncTestInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncTestInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncCheckFinishAllStationCompletedEventHandler(object sender, syncCheckFinishAllStationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncCheckFinishAllStationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncCheckFinishAllStationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void beTrueCompletedEventHandler(object sender, beTrueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class beTrueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal beTrueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncOrderInfoCompletedEventHandler(object sender, syncOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncInStockDocInfoCompletedEventHandler(object sender, syncInStockDocInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncInStockDocInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncInStockDocInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncIMEIInfoCompletedEventHandler(object sender, syncIMEIInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncIMEIInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncIMEIInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncSaveMidInfoCompletedEventHandler(object sender, syncSaveMidInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncSaveMidInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncSaveMidInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncSupplierInfoCompletedEventHandler(object sender, syncSupplierInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncSupplierInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncSupplierInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncProductOrderInfoCompletedEventHandler(object sender, syncProductOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncProductOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncProductOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncOutStockDocInfoCompletedEventHandler(object sender, syncOutStockDocInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncOutStockDocInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncOutStockDocInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncCheckStationCompletedEventHandler(object sender, syncCheckStationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncCheckStationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncCheckStationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncAllotDocInfoCompletedEventHandler(object sender, syncAllotDocInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncAllotDocInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncAllotDocInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncSalesOrderInfoCompletedEventHandler(object sender, syncSalesOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncSalesOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncSalesOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncCustomerInfoCompletedEventHandler(object sender, syncCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncMaterialInfoCompletedEventHandler(object sender, syncMaterialInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncMaterialInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncMaterialInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void replaceCompletedEventHandler(object sender, replaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class replaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal replaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncBomInfoCompletedEventHandler(object sender, syncBomInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncBomInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncBomInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncSetStationCompletedEventHandler(object sender, syncSetStationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncSetStationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncSetStationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncUploadParametersCompletedEventHandler(object sender, syncUploadParametersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncUploadParametersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncUploadParametersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void syncProductMaterialInfoCompletedEventHandler(object sender, syncProductMaterialInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncProductMaterialInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncProductMaterialInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591